package svm.corba.abstraction.controller;


/**
* svm/corba/abstraction/controller/Controller.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from controller/Controller.idl
* Sonntag, 11. November 2012 18:20 Uhr MEZ
*/

public interface Controller extends ControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Controller
