package svm.corba.abstraction.cto.contest;


/**
* svm/corba/abstraction/cto/contest/CTOContest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOContest.idl
* Montag, 12. November 2012 18:26 Uhr MEZ
*/

public interface CTOContest extends CTOContestOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOContest
