package svm.corba.abstraction.cto.contest;


/**
* svm/corba/abstraction/cto/contest/CTOContestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOContest.idl
* Montag, 12. November 2012 18:26 Uhr MEZ
*/

public interface CTOContestOperations  extends svm.corba.abstraction.cto.CTOOperations
{
} // interface CTOContestOperations
