package svm.corba.abstraction.cto.contest;


import svm.corba.abstraction.exceptions.LogicException;

/**
* svm/corba/abstraction/cto/contest/CTOContestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOContest.idl
* Dienstag, 13. November 2012 15:25 Uhr MEZ
*/

public interface CTOContestOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
  long startDate ();
  long endDate ();
  float fee ();
  svm.corba.abstraction.cto.contactDetails.CTOContactDetails contactDetails () throws LogicException;
} // interface CTOContestOperations
