package svm.corba.abstraction.cto.contest;


/**
* svm/corba/abstraction/cto/contest/CTOContestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOContest.idl
* Dienstag, 13. November 2012 14:54 Uhr MEZ
*/

public interface CTOContestOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
  int startDate ();
  int endDate ();
  float fee ();
  svm.corba.abstraction.cto.contactDetails.CTOContactDetails contactDetails ();
} // interface CTOContestOperations
