package svm.corba.abstraction.cto.contactDetails;


/**
* svm/corba/abstraction/cto/contactDetails/CTOContactDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOContactDetails.idl
* Mittwoch, 14. November 2012 08:42 Uhr MEZ
*/

public interface CTOContactDetails extends CTOContactDetailsOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOContactDetails
