package svm.corba.abstraction.cto.match;


/**
* svm/corba/abstraction/cto/match/CTOMatchOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatch.idl
* Dienstag, 13. November 2012 14:54 Uhr MEZ
*/

public interface CTOMatchOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
  int startDate ();
  int endDate ();
  boolean canceled ();
  String description ();
  String remarks ();
  int resultAway ();
  int resultHome ();
  svm.corba.abstraction.cto.team.CTOTeam homeTeam ();
  svm.corba.abstraction.cto.team.CTOTeam awayTeam ();
  svm.corba.abstraction.cto.matchType.CTOMatchType matchType ();
  svm.corba.abstraction.cto.contactDetails.CTOContactDetails contactDetails ();
} // interface CTOMatchOperations
