package svm.corba.abstraction.cto.match;


/**
* svm/corba/abstraction/cto/match/CTOMatchOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatch.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public interface CTOMatchOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
  long startDate ();
  long endDate ();
  boolean canceled ();
  String description ();
  String remarks ();
  String phone1 ();
  String phone2 ();
  String email1 ();
  String email2 ();
  String fax ();
  String street ();
  String streetNumber ();
  String coordLat ();
  String coordLong ();
  String countryCode ();
  String postalCode ();
  String placeName ();
  String district ();
  String homeTeam ();
  String awayTeam ();
  int resultAway ();
  int resultHome ();
} // interface CTOMatchOperations
