package svm.corba.abstraction.cto.match;


/**
* svm/corba/abstraction/cto/match/CTOMatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatch.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public interface CTOMatch extends CTOMatchOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOMatch
