package svm.corba.abstraction.cto.match;

/**
* svm/corba/abstraction/cto/match/CTOMatchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatch.idl
* Dienstag, 13. November 2012 15:48 Uhr MEZ
*/

public final class CTOMatchHolder implements org.omg.CORBA.portable.Streamable
{
  public svm.corba.abstraction.cto.match.CTOMatch value = null;

  public CTOMatchHolder ()
  {
  }

  public CTOMatchHolder (svm.corba.abstraction.cto.match.CTOMatch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = svm.corba.abstraction.cto.match.CTOMatchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    svm.corba.abstraction.cto.match.CTOMatchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return svm.corba.abstraction.cto.match.CTOMatchHelper.type ();
  }

}
