package svm.corba.abstraction.cto.auth;


/**
* svm/corba/abstraction/cto/auth/CTOAuth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOAuth.idl
* Sonntag, 11. November 2012 18:20 Uhr MEZ
*/

public interface CTOAuth extends CTOAuthOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOAuth
