package svm.corba.abstraction.cto.auth;


/**
* svm/corba/abstraction/cto/auth/CTOAuthOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOAuth.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public interface CTOAuthOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String firstName ();
  String lastName ();
  String username ();
  String title ();
} // interface CTOAuthOperations
