package svm.corba.abstraction.controller.login;


/**
* svm/corba/abstraction/controller/login/CorbaLoginController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from controller/CorbaLoginController.idl
* Mittwoch, 14. November 2012 14:43 Uhr MEZ
*/

public interface CorbaLoginController extends CorbaLoginControllerOperations, svm.corba.abstraction.controller.Controller, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaLoginController
