package svm.corba.abstraction.cto;


/**
* svm/corba/abstraction/cto/CTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTO.idl
* Mittwoch, 14. November 2012 14:43 Uhr MEZ
*/

public interface CTO extends CTOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTO
