package svm.corba.abstraction.cto;


/**
* svm/corba/abstraction/cto/CTOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTO.idl
* Dienstag, 13. November 2012 16:05 Uhr MEZ
*/

public interface CTOOperations 
{
  int CTOid ();
} // interface CTOOperations
