package svm.corba.abstraction.cto.location;


/**
* svm/corba/abstraction/cto/location/CTOLocation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOLocation.idl
* Dienstag, 13. November 2012 16:05 Uhr MEZ
*/

public interface CTOLocation extends CTOLocationOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOLocation
