package svm.corba.abstraction.cto.location;


/**
* svm/corba/abstraction/cto/location/CTOLocationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOLocation.idl
* Dienstag, 13. November 2012 14:54 Uhr MEZ
*/

public abstract class CTOLocationPOA extends org.omg.PortableServer.Servant
 implements svm.corba.abstraction.cto.location.CTOLocationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_countryCode", new java.lang.Integer (0));
    _methods.put ("_get_postalCode", new java.lang.Integer (1));
    _methods.put ("_get_placeName", new java.lang.Integer (2));
    _methods.put ("_get_district", new java.lang.Integer (3));
    _methods.put ("_get_province", new java.lang.Integer (4));
    _methods.put ("_get_community", new java.lang.Integer (5));
    _methods.put ("_get_coordLat", new java.lang.Integer (6));
    _methods.put ("_get_coordLong", new java.lang.Integer (7));
    _methods.put ("_get_CTOid", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // svm/corba/abstraction/cto/location/CTOLocation/_get_countryCode
       {
         String $result = null;
         $result = this.countryCode ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // svm/corba/abstraction/cto/location/CTOLocation/_get_postalCode
       {
         String $result = null;
         $result = this.postalCode ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // svm/corba/abstraction/cto/location/CTOLocation/_get_placeName
       {
         String $result = null;
         $result = this.placeName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // svm/corba/abstraction/cto/location/CTOLocation/_get_district
       {
         String $result = null;
         $result = this.district ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // svm/corba/abstraction/cto/location/CTOLocation/_get_province
       {
         String $result = null;
         $result = this.province ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // svm/corba/abstraction/cto/location/CTOLocation/_get_community
       {
         String $result = null;
         $result = this.community ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // svm/corba/abstraction/cto/location/CTOLocation/_get_coordLat
       {
         String $result = null;
         $result = this.coordLat ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // svm/corba/abstraction/cto/location/CTOLocation/_get_coordLong
       {
         String $result = null;
         $result = this.coordLong ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // svm/corba/abstraction/cto/CTO/_get_CTOid
       {
         int $result = (int)0;
         $result = this.CTOid ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:svm/corba/abstraction/cto/location/CTOLocation:1.0", 
    "IDL:svm/corba/abstraction/cto/CTO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CTOLocation _this() 
  {
    return CTOLocationHelper.narrow(
    super._this_object());
  }

  public CTOLocation _this(org.omg.CORBA.ORB orb) 
  {
    return CTOLocationHelper.narrow(
    super._this_object(orb));
  }


} // class CTOLocationPOA
