#ifndef _CTO
    #include <cto/CTO.idl>
    #define _CTO
#endif
#ifndef _CTOContactDetails
    #include <cto/CTOContactDetails.idl>
    #define _CTOContactDetails
#endif
#ifndef _LogicException
     #include <exceptions/LogicException.idl>
     #define _LogicException
#endif

module svm { module corba { module abstraction {
    module cto { module contest {
        interface CTOContest : CTO {

            readonly attribute string name;
            readonly attribute long long startDate;
            readonly attribute long long endDate;
            readonly attribute float fee;

            readonly attribute string phone1;
            readonly attribute string phone2;
            readonly attribute string email1;
            readonly attribute string email2;
            readonly attribute string fax;
            readonly attribute string street;
            readonly attribute string streetNumber;
            readonly attribute string coordLat;
            readonly attribute string coordLong;
            readonly attribute string countryCode;
            readonly attribute string postalCode;
            readonly attribute string placeName;
            readonly attribute string district;
            readonly attribute string sport;
            readonly attribute boolean finished;

        };
    }; };
}; }; };