#ifndef _CTO
    #include <cto/CTO.idl>
    #define _CTO
#endif
#ifndef _CTOContactDetails
      #include <cto/CTOContactDetails.idl>
      #define _CTOContactDetails
#endif
#ifndef _CTOMatchType
      #include <cto/CTOMatchType.idl>
      #define _CTOMatchType
#endif
#ifndef _CTOTeam
      #include <cto/CTOTeam.idl>
      #define _CTOTeam
#endif
#ifndef _LogicException
    #include <exceptions/LogicException.idl>
    #define _LogicException
#endif

module svm { module corba { module abstraction {
    module cto { module match {
        interface CTOMatch : CTO {

            readonly attribute string name;
            readonly attribute long long startDate;
            readonly attribute long long endDate;
            readonly attribute boolean canceled;
            readonly attribute string description;
            readonly attribute string remarks;
            readonly attribute string phone1;
            readonly attribute string phone2;
            readonly attribute string email1;
            readonly attribute string email2;
            readonly attribute string fax;
            readonly attribute string street;
            readonly attribute string streetNumber;
            readonly attribute string coordLat;
            readonly attribute string coordLong;
            readonly attribute string countryCode;
            readonly attribute string postalCode;
            readonly attribute string placeName;
            readonly attribute string district;
            readonly attribute string homeTeam;
            readonly attribute string awayTeam;
            readonly attribute long resultAway;
            readonly attribute long resultHome;
        };
    }; };
}; }; };