package svm.corba.abstraction.cto.matchType;


/**
* svm/corba/abstraction/cto/matchType/CTOMatchTypeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatchType.idl
* Mittwoch, 14. November 2012 08:42 Uhr MEZ
*/

public interface CTOMatchTypeOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
} // interface CTOMatchTypeOperations
