package svm.corba.abstraction.cto.matchType;


/**
* svm/corba/abstraction/cto/matchType/CTOMatchType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMatchType.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public interface CTOMatchType extends CTOMatchTypeOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOMatchType
