package svm.corba.abstraction.cto.team;


/**
* svm/corba/abstraction/cto/team/CTOTeamOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOTeam.idl
* Montag, 12. November 2012 18:27 Uhr MEZ
*/

public interface CTOTeamOperations  extends svm.corba.abstraction.cto.CTOOperations
{
} // interface CTOTeamOperations
