package svm.corba.abstraction.cto.team;


/**
* svm/corba/abstraction/cto/team/CTOTeam.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOTeam.idl
* Dienstag, 13. November 2012 15:48 Uhr MEZ
*/

public interface CTOTeam extends CTOTeamOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOTeam
