package svm.corba.abstraction.cto.team;


/**
* svm/corba/abstraction/cto/team/CTOTeamOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOTeam.idl
* Mittwoch, 14. November 2012 08:42 Uhr MEZ
*/

public interface CTOTeamOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String name ();
} // interface CTOTeamOperations
