package svm.corba.abstraction.controller.member;


/**
* svm/corba/abstraction/controller/member/CorbaMemberController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from controller/CorbaMemberController.idl
* Mittwoch, 14. November 2012 08:42 Uhr MEZ
*/

public interface CorbaMemberController extends CorbaMemberControllerOperations, svm.corba.abstraction.controller.Controller, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaMemberController
