package svm.corba.abstraction;


/**
* svm/corba/abstraction/SVMExportOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Export.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public interface SVMExportOperations 
{
  svm.corba.abstraction.sequences.Teams getListOfTeams () throws svm.corba.abstraction.exceptions.RegisterException;
  svm.corba.abstraction.sequences.Contests getListOfContestsByDate (long date) throws svm.corba.abstraction.exceptions.RegisterException;
  svm.corba.abstraction.sequences.Contests getListOfContestsByTeam (svm.corba.abstraction.cto.team.CTOTeam team) throws svm.corba.abstraction.exceptions.RegisterException;
  svm.corba.abstraction.sequences.Matches getListOfMatches (svm.corba.abstraction.cto.contest.CTOContest contest) throws svm.corba.abstraction.exceptions.RegisterException;
} // interface SVMExportOperations
