package svm.corba.abstraction;


/**
* svm/corba/abstraction/SVMExport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Export.idl
* Dienstag, 13. November 2012 15:25 Uhr MEZ
*/

public interface SVMExport extends SVMExportOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SVMExport
