package svm.corba.abstraction.cfactory;


/**
* svm/corba/abstraction/cfactory/CorbaControllerFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaControllerFactory.idl
* Mittwoch, 14. November 2012 14:43 Uhr MEZ
*/

public interface CorbaControllerFactoryOperations 
{
  svm.corba.abstraction.controller.login.CorbaLoginController getCorbaLoginController () throws svm.corba.abstraction.exceptions.RegisterException;
  svm.corba.abstraction.controller.member.CorbaMemberController getMemberController (svm.corba.abstraction.cto.auth.CTOAuth auth) throws svm.corba.abstraction.exceptions.RegisterException, svm.corba.abstraction.exceptions.AuthNotFoundException;
} // interface CorbaControllerFactoryOperations
