package svm.corba.abstraction.cfactory;

/**
* svm/corba/abstraction/cfactory/CorbaControllerFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaControllerFactory.idl
* Montag, 12. November 2012 18:27 Uhr MEZ
*/

public final class CorbaControllerFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public svm.corba.abstraction.cfactory.CorbaControllerFactory value = null;

  public CorbaControllerFactoryHolder ()
  {
  }

  public CorbaControllerFactoryHolder (svm.corba.abstraction.cfactory.CorbaControllerFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = svm.corba.abstraction.cfactory.CorbaControllerFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    svm.corba.abstraction.cfactory.CorbaControllerFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return svm.corba.abstraction.cfactory.CorbaControllerFactoryHelper.type ();
  }

}
