package svm.corba.abstraction.cfactory;


/**
* svm/corba/abstraction/cfactory/CorbaControllerFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaControllerFactory.idl
* Sonntag, 11. November 2012 18:20 Uhr MEZ
*/

public interface CorbaControllerFactory extends CorbaControllerFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaControllerFactory
