package svm.corba.abstraction.sequences;


/**
* svm/corba/abstraction/sequences/Contests.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Export.idl
* Montag, 12. November 2012 18:27 Uhr MEZ
*/

public final class Contests implements org.omg.CORBA.portable.IDLEntity
{
  public svm.corba.abstraction.cto.contest.CTOContest contests[] = null;

  public Contests ()
  {
  } // ctor

  public Contests (svm.corba.abstraction.cto.contest.CTOContest[] _contests)
  {
    contests = _contests;
  } // ctor

} // class Contests
