package svm.corba.abstraction.sequences;


/**
* svm/corba/abstraction/sequences/Matches.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Export.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public final class Matches implements org.omg.CORBA.portable.IDLEntity
{
  public svm.corba.abstraction.cto.match.CTOMatch matches[] = null;

  public Matches ()
  {
  } // ctor

  public Matches (svm.corba.abstraction.cto.match.CTOMatch[] _matches)
  {
    matches = _matches;
  } // ctor

} // class Matches
