package svm.corba.abstraction.sequences;


/**
* svm/corba/abstraction/sequences/Teams.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Export.idl
* Dienstag, 13. November 2012 15:25 Uhr MEZ
*/

public final class Teams implements org.omg.CORBA.portable.IDLEntity
{
  public svm.corba.abstraction.cto.team.CTOTeam teams[] = null;

  public Teams ()
  {
  } // ctor

  public Teams (svm.corba.abstraction.cto.team.CTOTeam[] _teams)
  {
    teams = _teams;
  } // ctor

} // class Teams
