#ifndef  _RegisterException
    #include <exceptions/RegisterException.idl>
    #define _RegisterException
#endif
#ifndef  _UnknownException
    #include <exceptions/UnknownException.idl>
    #define _UnknownException
#endif
#ifndef  _AuthNotFoundException
    #include <exceptions/AuthNotFoundException.idl>
    #define _AuthNotFoundException
#endif
#ifndef  _ControllerNotStartedException
    #include <exceptions/ControllerNotStartedException.idl>
    #define _ControllerNotStartedException
#endif

#ifndef _CTO
    #include <cto/CTO.idl>
    #define _CTO
#endif
#ifndef _CTOAuth
    #include <cto/CTOAuth.idl>
    #define _CTOAuth
#endif

#ifndef _Controller
    #include <controller/Controller.idl>
    #define _Controller
#endif
#ifndef _CorbaLoginController
    #include <controller/CorbaLoginController.idl>
    #define _CorbaLoginController
#endif
#ifndef _CorbaMemberController
    #include <controller/CorbaMemberController.idl>
    #define _CorbaMemberController
#endif