#ifndef _CorbaLoginController
    #include <controller/CorbaLoginController.idl>
    #define _CorbaLoginController
#endif
#ifndef _CorbaMemberController
    #include <controller/CorbaMemberController.idl>
    #define _CorbaMemberController
#endif

#ifndef  _RegisterException
    #include <exceptions/RegisterException.idl>
    #define _RegisterException
#endif
#ifndef  _AuthNotFoundException
    #include <exceptions/AuthNotFoundException.idl>
    #define _AuthNotFoundException
#endif

module svm { module corba { module abstraction {
    module cfactory {
        interface CorbaControllerFactory {
            controller::login::CorbaLoginController getCorbaLoginController() raises (exceptions::RegisterException);
            controller::member::CorbaMemberController getMemberController(in cto::auth::CTOAuth auth) raises (exceptions::RegisterException, exceptions::AuthNotFoundException);
        };
    };
}; }; };