package svm.corba.abstraction.exceptions;


/**
* svm/corba/abstraction/exceptions/ControllerNotStartedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions/ControllerNotStartedException.idl
* Sonntag, 11. November 2012 18:20 Uhr MEZ
*/

public final class ControllerNotStartedException extends org.omg.CORBA.UserException
{

  public ControllerNotStartedException ()
  {
    super(ControllerNotStartedExceptionHelper.id());
  } // ctor


  public ControllerNotStartedException (String $reason)
  {
    super(ControllerNotStartedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ControllerNotStartedException
