package svm.corba.abstraction.exceptions;


/**
* svm/corba/abstraction/exceptions/LogicException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions/LogicException.idl
* Dienstag, 13. November 2012 15:25 Uhr MEZ
*/

public final class LogicException extends org.omg.CORBA.UserException
{

  public LogicException ()
  {
    super(LogicExceptionHelper.id());
  } // ctor


  public LogicException (String $reason)
  {
    super(LogicExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class LogicException
