package svm.corba.abstraction.exceptions;


/**
* svm/corba/abstraction/exceptions/NotAllowException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions/NotAllowException.idl
* Dienstag, 13. November 2012 16:05 Uhr MEZ
*/

public final class NotAllowException extends org.omg.CORBA.UserException
{

  public NotAllowException ()
  {
    super(NotAllowExceptionHelper.id());
  } // ctor


  public NotAllowException (String $reason)
  {
    super(NotAllowExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotAllowException
