package svm.corba.abstraction.exceptions;


/**
* svm/corba/abstraction/exceptions/RegisterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions/RegisterException.idl
* Montag, 12. November 2012 18:26 Uhr MEZ
*/

public final class RegisterException extends org.omg.CORBA.UserException
{

  public RegisterException ()
  {
    super(RegisterExceptionHelper.id());
  } // ctor


  public RegisterException (String $reason)
  {
    super(RegisterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class RegisterException
