package svm.corba.abstraction.exceptions;

/**
* svm/corba/abstraction/exceptions/UnknownExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions/UnknownException.idl
* Freitag, 16. November 2012 08:43 Uhr MEZ
*/

public final class UnknownExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public svm.corba.abstraction.exceptions.UnknownException value = null;

  public UnknownExceptionHolder ()
  {
  }

  public UnknownExceptionHolder (svm.corba.abstraction.exceptions.UnknownException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = svm.corba.abstraction.exceptions.UnknownExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    svm.corba.abstraction.exceptions.UnknownExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return svm.corba.abstraction.exceptions.UnknownExceptionHelper.type ();
  }

}
