package svm.corba.abstraction.cto.member;


/**
* svm/corba/abstraction/cto/member/CTOMemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMember.idl
* Mittwoch, 14. November 2012 14:43 Uhr MEZ
*/

public interface CTOMemberOperations  extends svm.corba.abstraction.cto.CTOOperations
{
  String userName ();
  String firstName ();
  String lastName ();
  String title ();
  String socialNumber ();
  long birthDate ();
  String gender ();
  long entryDate ();
  String phone1 ();
  String phone2 ();
  String email1 ();
  String email2 ();
  String fax ();
  String street ();
  String streetNumber ();
  String coordLat ();
  String coordLong ();
  String countryCode ();
  String postalCode ();
  String placeName ();
  String district ();
} // interface CTOMemberOperations
