package svm.corba.abstraction.cto.member;


/**
* svm/corba/abstraction/cto/member/CTOMember.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cto/CTOMember.idl
* Montag, 12. November 2012 18:26 Uhr MEZ
*/

public interface CTOMember extends CTOMemberOperations, svm.corba.abstraction.cto.CTO, org.omg.CORBA.portable.IDLEntity 
{
} // interface CTOMember
